<!DOCTYPE html>
<html>
<head>
	<title><?php echo $pageName;?></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
	<meta name="description" content=""/>
	<meta name="keywords" content=""/>
	<meta name="Maged" content="Author name" />
	<meta name="theme-color" content="#014656" />
	<link rel="stylesheet" href="<?php echo $css ?>bootstrap.css">
	<link rel="stylesheet" href="<?php echo $css ?>all.css">
	<link rel="stylesheet" href="<?php echo $css ?>fontawesome.css">
	<link rel="stylesheet" href="<?php echo $css ?>mystyle.css">
</head>
<body>
